#!/bin/sh
# 清除屏幕
clear
echo "Press Ctrl+c at any time to quit."
# 获取当前目录名称
defaultN=`basename $PWD`
# 应用名称
read -p "name:" inputN
if [ ! -n "$inputN" ];then
    name=$defaultN
else 
    name=$inputN
fi

# 版本号
defaultV="1.0.0"
read -p "version($defaultV):" inputV
if [ ! -n "$inputV" ];then
    version=$defaultV
else 
    version=$inputV
fi
echo $version

# 开始编译
echo "building..."
CGO_ENABLED=0
GOOS=windows
GOARCH=386
go build -o $name.$version.exe main.go
echo "end..."
